name: cyberprop
description: 'Aplikasi Properti.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter_localization: ^0.2.2
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  localization: ^2.1.1
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.png
    - assets/logo-new.png
