// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm72t-VyWEBsrQOSSD4-nsvtur4kDxdek',
    appId: '1:247073690698:web:e9fe609148ba2291af82b3',
    messagingSenderId: '247073690698',
    projectId: 'cyberprop-proj',
    authDomain: 'cyberprop-proj.firebaseapp.com',
    storageBucket: 'cyberprop-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx2HV1l3XB5IKr--g1kIGNbihxom1rdHY',
    appId: '1:247073690698:android:02ebebbe962b43e7af82b3',
    messagingSenderId: '247073690698',
    projectId: 'cyberprop-proj',
    storageBucket: 'cyberprop-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrlk2yZer2UFT3V9pm_rSK5xi58AHppls',
    appId: '1:247073690698:ios:35309a6eb28e4786af82b3',
    messagingSenderId: '247073690698',
    projectId: 'cyberprop-proj',
    storageBucket: 'cyberprop-proj.appspot.com',
    iosBundleId: 'com.example.cyberphobeProject',
  );

}